baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jabbsaft Education'



theme = 'hugo-story'

[params]
favicon = true

[params.social]
linkedin = 'https://www.linkedin.com/in/msletfj/'
github = 'https://github.com/eembees/'
